const ADD_TO_CART = 'ADD_TO_CART'; 
const ADD_TO_CART_FROM_LIST = 'ADD_TO_CART_FROM_LIST'; 
const ASC_DEC = 'ASC_DEC'; 
const SELECT_ITEMS_FROM_CATEGORYS = 'SELECT_ITEMS_FROM_CATEGORYS';
const CLEAR_CART = 'CLEAR_CART'; 
const SET_PAGINATION = 'SET_PAGINATION'; 

export { ADD_TO_CART, ASC_DEC, ADD_TO_CART_FROM_LIST, SELECT_ITEMS_FROM_CATEGORYS, CLEAR_CART, SET_PAGINATION }